name: Build and Deploy this site

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Run Gatsby deploy manually'

permissions:
  contents: read # Required for actions/checkout@v3 to clone the repository
  pages: write   # Required for JamesIves/github-pages-deploy-action to push to gh-pages
  id-token: write # Required if you are using OIDC for deployments, good practice for Pages deployments.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Gatsby
        run: |
          npm install husky -g
          npx husky install
          chmod +x .husky/*
          npm install

      - name: Build Gatsby site
        run: |
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          folder: public
